apiVersion: v1
kind: Service
metadata:
  name: ts4nfdi-api-gateway-collection-statistics
spec:
  selector:
    app: ts4nfdi-api-gateway-collection-statistics
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP